name = "readerwrangler-relay"
main = "relay-worker.js"
compatibility_date = "2024-09-25"

[vars]
ALLOWED_ORIGINS = "https://www.amazon.com,https://readerwrangler.com,https://ron-l.github.io,http://localhost:8000"

[[kv_namespaces]]
binding = "RELAY_KV"
id = "4a445b412fb34860a896cfc145a67b9b"
